// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"user-service/internal/user"
)

type AuthPayload struct {
	Token string     `json:"token"`
	User  *user.User `json:"user"`
}

type Mutation struct {
}

type Query struct {
}
